development:
  clients:
    default:
      database: development
      hosts:
        - cluster0-shard-00-00-fhldl.mongodb.net:27017,
        - cluster0-shard-00-01-fhldl.mongodb.net:27017,
        - cluster0-shard-00-02-fhldl.mongodb.net:27017
      options:
        user: 'bunkmate_admin'
        password: '1r9sE2scn5Wyu4sH'
        auth_source: admin
        replica_set: Cluster0-shard-0
        ssl: true
  options:
test:
  clients:
    default:
      database: bm_test
      hosts:
        - cluster0-shard-00-00-fhldl.mongodb.net:27017,
      options:
        read:
          mode: :primary
        max_pool_size: 1
